Description: Fix issue with consoleauth after security fix.
 The fix for unit-tests here e02b45976fe4468ad70c886255f1af71652ce4f9
 accidentally removed a parameter that was being used from the
 _validate_console call. This adds it back.
Origin: upstream, https://review.openstack.org/#/c/24608/
Author: Vishvananda Ishaya <vishvananda@gmail.com>
Bug-Debian: http://bug.debian.org/703242
Bug-Ubuntu: https://code.launchpad.net/bugs/1156316
Date: Sun, 17 Mar 2013 19:42:44 +0000 (-0700)

diff --git a/nova/consoleauth/manager.py b/nova/consoleauth/manager.py
index 5690ef3..ac9b70d 100644
--- a/nova/consoleauth/manager.py
+++ b/nova/consoleauth/manager.py
@@ -84,7 +84,7 @@ class ConsoleAuthManager(manager.Manager):
 
         LOG.audit(_("Received Token: %(token)s, %(token_dict)s)"), locals())
 
-    def _validate_console(self, token):
+    def _validate_console(self, context, token):
         console_valid = False
         token_dict = self.tokens[token]
         try:
@@ -99,7 +99,7 @@ class ConsoleAuthManager(manager.Manager):
     def check_token(self, context, token):
         token_valid = token in self.tokens
         LOG.audit(_("Checking Token: %(token)s, %(token_valid)s)"), locals())
-        if token_valid and self._validate_console(token):
+        if token_valid and self._validate_console(context, token):
             return self.tokens[token]
 
     def delete_tokens_for_instance(self, context, instance_id):
